version: "3.9"

services:
  app:
    build: .
    container_name: bear_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: sh -c "npm run migrate && npm run seed && npm start"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: